// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieorukamS1VinNrDqtr175JoBJ-lj6k0',
    appId: '1:714859937171:web:ec2cf52fa8be6de4a4fc66',
    messagingSenderId: '714859937171',
    projectId: 'login-app-assignment-2',
    authDomain: 'login-app-assignment-2.firebaseapp.com',
    storageBucket: 'login-app-assignment-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf1NXh0Bq7sD2PGukQkFfDKjJTs645r1c',
    appId: '1:714859937171:android:720af9086338b031a4fc66',
    messagingSenderId: '714859937171',
    projectId: 'login-app-assignment-2',
    storageBucket: 'login-app-assignment-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFImw4qjdjYQGLd62T7tS_0158c9TMqY',
    appId: '1:714859937171:ios:d8b442baa7fb6a2ea4fc66',
    messagingSenderId: '714859937171',
    projectId: 'login-app-assignment-2',
    storageBucket: 'login-app-assignment-2.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );
}
